parameters:
    # Von tools/build2.ps1 erzeugt und ins Image kopiert
    app.gamedata_file: '%kernel.project_dir%/data/gamedata-server.json'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GameData:
        arguments:
            $file: '%app.gamedata_file%'

    App\Service\Altcha:
        arguments:
            $secret: '%kernel.secret%'
